// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'Ahoj': typeof import('./MapComponent')['MapComponent']
  }
}

export const Ahoj: typeof import('./MapComponent')['MapComponent'];
